wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.3
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1719997172
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.17.3
      6: 4.41.2
      8:
      - 1
      - 5
      - 12
      13: linux-x86_64
